### ISSUE TITLE
Firmware/Hardware

### ISSUE THREAD

**Issue by nico0481** [kentindell/canhack#4]
Hello Ken,

I'm quite confused with the use of 2 boards.
I noticed the difference with the Canis CANHack board vs the Canis CANPico ( includes MCP2518 transceiver), but what is the difference with the firmware? Which one is the best to use with CANHackTool kit?
What is the improvement with the controller?
It is not even clear for me.

Thank you

Regards

Nico

**Comment by kentindell** [comment]
The CANHack board has a CAN transceiver connected to the GPIO pins. The CANPico board has a CAN controller connected to the transceiver but also connects the transceiver to the same pins. 

The same firmware can be used on both boards. The API for the CAN controller will return an error when you try to use it on a CANHack board because there's nothing to talk to on the end of the SPI bus :-)
